---

- name: install avahi-utils
  apt:
    name:
      - avahi-utils
    update_cache: true
    state: present
  become: true

- name: copy sync scripts
  template:
    src: "{{ item }}"
    dest: "/usr/bin/"
    mode: '777'
  with_items:
    - backup_home
    - restore_home

- name: copy backup excludes
  copy:
    src: "{{ item }}"
    dest: "/home/{{ installation_os_user }}/.backup_excludes"
    owner: "{{ installation_os_user }}"
    group: "{{ installation_os_group }}"
  with_items:
    - backup_excludes

- name: copy switch_user script
  copy:
    src: "{{ item }}"
    dest: "/sbin/"
    mode: '744'
  with_items:
    - switch_user

- name: change prompt to reflect hostname change immediatly
  replace:
    path: "/home/{{ installation_os_user }}/.bashrc"
    regexp: '@\\h'
    replace: "@$(hostname)"
