---

- name: install avahi-utils
  apt:
    name:
      - avahi-utils
    update_cache: true
    state: present
  become: true

- name: copy new version sync scripts
  template:
    src: "{{ item }}"
    dest: "/usr/bin/"
    mode: '777'
  with_items:
    - backup_home
    - restore_home

- name: copy switch_user script
  copy:
    src: "{{ item }}"
    dest: "/sbin/"
    mode: '744'
  with_items:
    - switch_user

- name: change prompt to reflect hostname change immediatly
  replace:
    path: "/home/{{ installation_os_user }}/.bashrc"
    regexp: '@\\h'
    replace: "@$(hostname)"
