---
language: python
services: docker

env:
  global:
    - ROLE_NAME: tigerjython
  matrix:
    - MOLECULE_DISTRO: debian10

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME bassinator.$ROLE_NAME
  - cd bassinator.$ROLE_NAME
  - source source.me

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
