---

- name: install software packages
  ansible.builtin.apt:
    name:
      - tor
      - netcat-openbsd
      - openssh-server
    update_cache: true
    state: present
  become: true

- name: start sshd service
  ansible.builtin.service:
    name: ssh
    enabled: true
    state: started

- name: create tor hidden service dir
  ansible.builtin.file:
    path: "/var/lib/tor/ssh"
    mode: '0700'
    state: directory
    owner: 'debian-tor'
  notify:
    - restart tor

- name: write hidden service secret
  ansible.builtin.copy:
    content: "{{ onion_hidden_service_private_key_b64 | b64decode }}"
    dest: "/var/lib/tor/ssh/hs_ed25519_secret_key"
    mode: '0644'
    owner: debian-tor
    group: debian-tor
  when: onion_hidden_service_private_key_b64
  notify:
    - restart tor

- name: configure ssh hidden service
  ansible.builtin.blockinfile:
    path: "/etc/tor/torrc"
    mode: '0644'
    block: |
      HiddenServiceDir /var/lib/tor/ssh/
      HiddenServicePort 2222 127.0.0.1:22
  notify:
    - restart tor

- name: create .ssh config dir
  ansible.builtin.file:
    path: "/home/{{ installation_os_user }}/.ssh"
    mode: '0700'
    state: directory
    owner: "{{ installation_os_user }}"
    group: "{{ installation_os_group }}"

- name: configure ssh client proxy command
  ansible.builtin.blockinfile:
    path: "/home/{{ installation_os_user }}/.ssh/config"
    mode: '0644'
    create: true
    owner: "{{ installation_os_user }}"
    group: "{{ installation_os_group }}"
    insertbefore: BOF
    block: |
      # Wildcard to match all tor hosts
      Host *.onion *-tor
      ProxyCommand nc -X 5 -x 127.0.0.1:9050 %h %p
      CheckHostIP  no
      Compression  yes
      Protocol     2

- name: allow password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#{0,1}PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    state: present
