---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: raspbian
    image:  ${SYNC_SERVER_IMAGE:-"balenalib/raspberrypi4-64-debian-python"}
provisioner:
  name: ansible
  inventory:
    host_vars:
      raspbian:
        users:
        - username: testuser
          fullname: test user
          ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
          comment: Test User
          group: testcommon
          state: present

        - username: testadmin
          fullname: test admin
          ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
          comment: Test Admin User
          group: admins
          groups: sudo
          state: present
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
verifier:
  name: ansible
