---
- name: Destroy
  hosts: containers
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:

    - name: Destroy a container
      community.docker.docker_container:
        name: "{{ inventory_hostname }}"
        state: absent
      delegate_to: 127.0.0.1


    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: 0600
      when: server.changed | default(false) | bool
