local:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/venv/bin/python"

server:
  hosts:
    epic-docker-host:
      ansible_connection: docker
      ansible_user: root
      image: balenalib/amd64-debian-python
