---
users: 
  - username: testuser
    fullname: test user
    uid: 1103
    password: "$y$j9T$JtyMSJjB9l/pW9W4APb341$GD993mZqQLeuaxKIogpA0HtQKUmoCY72gvfOQs.UQm5"
    update_password: on_create
    comment: Test User
    group: admins
    gid: 1101
    state: present
