---

- name: Install pip
  ansible.builtin.command:
    cmd: "python3 /tmp/get-pip.py"

- name: Reload docker
  ansible.builtin.service:
    name: docker
    state: reloaded
  when: not unit_test

- name: Restart docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: restarted
