---

- name: Install pip
  ansible.builtin.command:
    cmd: "python3 /tmp/get-pip.py"

- name: Reload docker
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: restarted
