---
dependency:
  name: shell
  command: "ansible-galaxy collection install ../"
driver:
  name: delegated
platforms:
  - name: epic-docker-host
    groups:
      - container
      - raspberries
  - name: epic-backup
    groups:
      - container
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
  inventory:
    links:
      host_vars: ${INVENTORY_FILE:-"host_vars"}
      group_vars: ${INVENTORY_FILE:-"group_vars"}
  env:
    MOLECULE_PROJECT_DIRECTORY: ${MOLECULE_PROJECT_DIRECTORY} 
verifier:
  name: ansible
