---
- name: run container configuration playbook
  import_playbook: ../../playbooks/configure_epicbackup.yml

- name: run docker-host configuration playbook
  import_playbook: ../../playbooks/configure_server.yml

- name: run container configuration playbook
  import_playbook: ../../playbooks/configure_epicraspberries.yml

- name: run actions_runner configuration playbook
  import_playbook: ../../playbooks/configure_actions_runner.yml
