---
- name: set image name to use for provision
  hosts: container
  connection: local
  gather_facts: false
  tasks:

  - set_fact:
      image: "{{ item.image }}" 
    when: item.name == inventory_hostname
    with_items: "{{ molecule_yml.platforms }}"

- name: create testcontainer
  import_playbook: ../../playbooks/provision_container.yml

#- name: create raspberries (also as container for local testing)
#  hosts: raspberries
#  gather_facts: false
#  connection: local
#  tasks:
#    - name: Start container
#      docker_container:
#        name: "{{ inventory_hostname }}"
#        image: "{{ image }}"
#        command: ["sleep", "infinity"]
#      delegate_to: 127.0.0.1
