local:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/venv/bin/python"

containers:
  hosts:
    ssh_tor:
      ansible_connection: docker
      ansible_user: root
      image: balenalib/raspberrypi4-64-debian-python
      users:
      - username: testuser
        fullname: test user
        password: buaepolojoku
        update_password: on_create
        ssh_pub_key:
        comment: Test User
        group: testcommon

      - username: testadmin
        fullname: test admin
        password: lepatevaxafo
        update_password: on_create
        ssh_pub_key:
        comment: Test Admin User
        group: admins
