---
dependency:
  name: shell
  command: "ansible-galaxy collection install .. --force"
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: epic-backup
    image:  ${CONTAINER_IMAGE:-"balenalib/raspberrypi4-64-debian-python"}
    groups:
      - container
      - epic_backup
  - name: epic-runner
    image:  ${CONTAINER_IMAGE:-"balenalib/raspberrypi4-64-debian-python"}
    groups:
      - container
      - actions_runner
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
  inventory:
    links:
      host_vars: ${INVENTORY_FILE:-"host_vars"}
      group_vars: ${INVENTORY_FILE:-"group_vars"}
  env:
    MOLECULE_PROJECT_DIRECTORY: ${MOLECULE_PROJECT_DIRECTORY} 
verifier:
  name: ansible
