---
- name: Prepare
  hosts: actions_runner
  tasks:

  - name: upgrade packages
    ansible.builtin.apt:
      upgrade: true
      update_cache: true

  - name: add user group
    user:
      name: 'pi'
      state: present

  - name: add user
    user:
      name: 'pi'
      group: 'pi'
