--- # This is an example playbook to execute Ansible tests.

- name: Verify host
  hosts: localhost
  gather_facts: false
  tasks:

  - name: Get infos on container
    docker_container_info:
      name: ssh_tor
    register: result

  - name: Assert container is running
    assert:
      that:
      - result.exists
      - result.container['State']['Status'] == "running"
  
  - name: Does container exist?
    debug:
      msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"
  
  - name: Print the status of the container
    debug:
      msg: "The container status is {{ result.container['State']['Status'] }}"
    when: result.exists

- name: Verify ssh_tor
  hosts: ssh_tor
  gather_facts: false
  tasks:

  - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
    community.crypto.openssh_keypair:
      path: ~/.ssh/id_ssh_rsa
 
  - name: add own pub key to allowed hosts
    ansible.builtin.copy:
      src: ~/.ssh/id_ssh_rsa.pub
      dest: ~/.ssh/authorized_keys
      remote_src: yes

  - name: get onion hostname
    ansible.builtin.command: cat /var/lib/tor/ssh/hostname
    register: hostname
    changed_when: false

  - debug: msg="onion hostname is {{ hostname.stdout }}"

  - name: test ssh connecion via onion hidden service
    ansible.builtin.command: "ssh -oStrictHostKeyChecking=no -i ~/.ssh/id_ssh_rsa -o ConnectTimeout=5 -q {{ hostname.stdout }} exit"
    changed_when: false
    retries: 3
    delay: 10
    until: result is not failed
