---

- name: Verify host
  hosts: all
  gather_facts: false
  tasks:

  - name: Get infos on container
    docker_container_info:
      name: "{{ inventory_hostname }}"
    register: result
    delegate_to: localhost

  - name: Assert container is running
    assert:
      that:
      - result.exists
      - result.container['State']['Status'] == "running"
  
  - name: Does container exist?
    debug:
      msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"
  
  - name: Print the status of the container
    debug:
      msg: "The container status is {{ result.container['State']['Status'] }}"
    when: result.exists

- name: Verify ssh_tor
  hosts: epic-backup
  connection: docker
  gather_facts: false
  tasks:

  - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
    community.crypto.openssh_keypair:
      path: /home/testuser/.ssh/id_rsa
      owner: testuser
      group: testcommon
 
  - name: create ssh config dir
    ansible.builtin.file:
      path: /home/testuser/.ssh
      owner: testuser
      group: testcommon
      state: directory
 
  - name: add own pub key to allowed hosts
    ansible.builtin.copy:
      src: /home/testuser/.ssh/id_rsa.pub
      dest: /home/testuser/.ssh/authorized_keys
      force: true
      owner: testuser
      group: testcommon
      remote_src: yes

  - name: get onion hostname
    ansible.builtin.command: cat /var/lib/tor/ssh/hostname
    register: hostname
    changed_when: false

  - debug: msg="onion hostname is {{ hostname.stdout }}"

  - name: test ssh connection via onion hidden service
    ansible.builtin.command: "ssh -oStrictHostKeyChecking=no -o ConnectTimeout=10 -q testuser@{{ hostname.stdout }} -p 2222 exit"
    changed_when: false
    register: result
    retries: 5
    delay: 10
    until: result is not failed
    become: true
    become_user: testuser

- name: Verify rsync backup
  hosts: epic-backup
  gather_facts: false
  tasks:

  - name: create file to test backup
    ansible.builtin.copy:
      content: '# file to test backup capability'
      dest: ~/testfile

  - name: create destination backup dir
    ansible.builtin.file:
      path: /home/testuser/backups
      owner: testuser
      group: testcommon
      state: directory

  - name: test rsync via ssh onion hidden service
    ansible.builtin.command: "rsync -ai -e 'ssh -p 2222' ~/testfile testuser@{{ hostname.stdout }}:~/backups"
    register: rsync
    changed_when: rsync.stdout != ""

  - name: Get stats about backup destination testfile
    stat:
      path: /home/testuser/backups/testfile
    changed_when: false
    register: result


  - name: Assert testfile was written to backup destination
    assert:
      that:
      - result.stat.exists
