---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: raspbian
    image:  ${SYNC_SERVER_IMAGE:-"balenalib/raspberrypi4-64-debian-python"}
    groups:
      - external_disk
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
verifier:
  name: ansible
scenario:
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - syntax
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
