---
installation_os_user: root
users:
- username: testuser
  fullname: test user
  password: buaepolojoku
  update_password: on_create
  ssh_pub_key:
  comment: Test User
  group: testcommon
  state: present
          
- username: testadmin
  fullname: test admin
  password: lepatevaxafo
  update_password: on_create
  ssh_pub_key:
  comment: Test Admin User
  group: admins
  state: present

docker_volumes:
  - name: home_backup
    path: /home

docker_keep_volumes: false
