# This is a basic workflow to help you get started with Actions

name: CI Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt -y upgrade
          curl -fsSL https://get.docker.com | sudo bash
          sudo apt install python3 python3-pip virtualenv

      - name: Run molecule tests
        run: |
          virtualenv -p python3 venv
          source venv/bin/activate
          pip install ansible molecule molecule-docker yamllint ansible-lint
          molecule test
