# This is a basic workflow to help you get started with Actions

name: Integration Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt -y upgrade
          curl -fsSL https://get.docker.com | sudo bash
          sudo apt -y install python3 python3-pip python3-venv

      - name: Run molecule tests
        run: |
          source source.me
          export CONTAINER_IMAGE=balenalib/amd64-debian-python
          export CPU_ARCHITECTURE=x64
          molecule test
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
