---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: raspbian
    image:  ${SYNC_SERVER_IMAGE:-"balenalib/raspberrypi4-64-debian-python"}
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
verifier:
  name: ansible
