---
- name: download argon fan control script
  ansible.builtin.get_url:
    url: https://download.argon40.com/argon1.sh
    dest: /tmp/argon1.sh
    mode: '0744'

- name: install argon fan control script
  ansible.builtin.shell: /tmp/argon1.sh
  args:
    executable: /bin/bash
    creates: /usr/bin/argonone-config
  register: argon_install
  changed_when: argon_install.stderr == ""

- name: Install parted command line tool
  apt:
    name: parted

- name: Read device information (always use unit when probing)
  community.general.parted: "device={{ disk_device }} unit=MiB"
  register: dev_info

- name: Remove all partitions from disk
  community.general.parted:
    device: "{{ disk_device }}"
    number: '{{ item.num }}'
    state: absent
  loop: '{{ dev_info.partitions }}'
  register: partitions
  when: dev_info.partitions | length > 1 or ( dev_info.partitions | length == 1 and dev_info.partitions[0].fstype != "ext4" )
  
- name: Create a new ext4 primary partition
  community.general.parted:
    device: "{{ disk_device }}"
    number: 1
    part_start: 0%
    part_end: 100%
    fs_type: "ext4"
    state: present
  when: dev_info.partitions | length == 0 or partitions.changed

- name: Create a ext4 filesystem on /dev/sdb1 and check disk blocks
  community.general.filesystem:
    fstype: ext4
    dev: "{{ disk_device }}"

- name: create /data mountpoint
  ansible.builtin.file:
    path: /data
    state: directory
    mode: '0755'

- name: Mount new partition
  ansible.posix.mount:
    path: /data
    src: "{{ disk_device }}"
    fstype: ext4
    state: present
