---
- name: download argon fan control script
  ansible.builtin.get_url:
    url: https://download.argon40.com/argon1.sh
    dest: /tmp/argon1.sh
    mode: '0744'

- name: install argon fan control script
  ansible.builtin.shell: /tmp/argon1.sh
  args:
    executable: /bin/bash
    creates: /usr/bin/argonone-config
  register: argon_install
