---
- name: setup epic docker container host
  hosts: raspberries
  become: true
  gather_facts: false
  tasks:

    - name: "setup docker"
      include_role:
        name: "einfachit.epicserver.docker"

- name: install argon fan control scripts
  hosts: argon_case
  become: true
  gather_facts: false
  tasks:

    - name: "Include argon case installation"
      include_role:
        name: "einfachit.epicserver.argon_case"
