---
- name: setup epic docker container host
  hosts: raspberries
  become: true
  gather_facts: false
  tasks:

  - name: "configure external drive"
    include_role:
      name: "einfachit.epicserver.ext_disk"
    vars:
      ext_disk_device: /dev/sda
      hext_disk_mountpoint: /var/lib/docker

  - name: "setup docker"
    include_role:
      name: "einfachit.epicserver.docker"


- name: install argon fan control scripts
  hosts: argon_case
  become: true
  gather_facts: false
  tasks:

    - name: "Include argon case installation"
      include_role:
        name: "einfachit.epicserver.argon_case"
