---
- name: setup epicRaspberries children clients
  hosts: epicraspberries
  become: true
  gather_facts: true
  vars:
    installation_os_user: pi
    installation_os_group: pi

  pre_tasks:

    - name: update apt cache with sudo apt-get --allow-releaseinfo-change update
      command: sudo apt-get --allow-releaseinfo-change update
      changed_when: false

    - name: Hold raspberrypi-kernel
      dpkg_selections:
        name: raspberrypi-kernel
        selection: hold

    - name: Upgrade the OS (apt-get upgrade)
      apt:
        upgrade: yes

  roles:
    - { role: bassinator.localisation }
    - { role: bassinator.mosquitto }
    - { role: bassinator.simplehttp }
#    - { role: bassinator.autoarchive }
    - { role: bassinator.pi_aseba }
    - { role: einfachit.epic.ssh_tor }
    - { role: einfachit.epic.net_sync }
    - { role: einfachit.epic.tigerjython }
  
  tasks:
    - name: Install scratch3 OS package
      apt:
        name: 'scratch3'
