---
- hosts: container:&epic-backup
  gather_facts: false
  connection: docker
  tasks:

    - name: install usefull software
      ansible.builtin.apt:
        name: vim
        state: present

    - name: "Include ssh_tor"
      include_role:
        name: "einfachit.epicserver.ssh_tor"
      vars:
        installation_os_user: root

    - name: "Include user mgmt"
      include_role:
        name: "einfachit.epicserver.users"
        
    - name: install rsync to backup container
      apt:
        name:
          - rsync
        update_cache: true
        state: present
      become: true
      
