---
- hosts: epic_backup
  gather_facts: false
  connection: docker
  pre_tasks:

    - name: install needed software
      ansible.builtin.apt:
        name:
          - rsync
        state: present

  tasks:
    - name: include role epic.users
      ansible.builtin.include_role:
        name: einfachit.epic.users

    - name: include role epic.ssh_tor
      ansible.builtin.include_role:
        name: einfachit.epic.ssh_tor
      vars:
         installation_os_user: root
         installation_os_group: root

#  roles:
#    - role: einfachit.epic.ssh_tor
#      vars:
#         installation_os_user: root
#         installation_os_group: root
#    - einfachit.epic.users

  post_tasks:
    - name: get onion hostname
      ansible.builtin.command: cat /var/lib/tor/ssh/hostname
      register: hostname
      changed_when: false
    
    - debug: msg="onion hostname is {{ hostname.stdout }}"
