---
- name: setup epicRaspberries children clients
  hosts: epicraspberries
  become: true
  gather_facts: true
  vars:
    installation_os_user: pi
    installation_os_group: pi

  roles:
    - { role: bassinator.localisation }
#    - { role: bassinator.mosquitto }
#    - { role: bassinator.simplehttp }
#    - { role: bassinator.autoarchive }
    - { role: einfachit.pi_aseba }
    - { role: einfachit.epic.ssh_tor }
    - { role: einfachit.epic.net_sync }
    - { role: einfachit.epic.tigerjython }
  
  tasks:
    - name: Install scratch3 OS package
      apt:
        name: 'scratch3'
      when: ansible_architecture == "aarch64"
