---
- hosts: epic_backup
  gather_facts: false
  connection: docker
  pre_tasks:

    - name: install usefull software
      ansible.builtin.apt:
        name: vim
        state: present
  roles:
    - role: einfachit.epic.ssh_tor
      vars:
         installation_os_user: root
         installation_os_group: root
    - einfachit.epic.users

  tasks:
    - name: install rsync to backup container
      apt:
        name:
          - rsync
        update_cache: true
        state: present
      become: true

  post_tasks:

    - name: get onion hostname
      ansible.builtin.command: cat /var/lib/tor/ssh/hostname
      register: hostname
      changed_when: false
    
    - debug: msg="onion hostname is {{ hostname.stdout }}"
