---
- name: configure external usb disk
  hosts: ext_disk
  become: true
  gather_facts: false
  tasks:

  - name: "configure external drive"
    include_role:
      name: "einfachit.epic.ext_disk"
    vars:
      ext_disk_device: /dev/sda
      hext_disk_mountpoint: /var/lib/docker


- name: setup epic docker container host
  hosts: docker_host
  become: true
  gather_facts: false
  tasks:

  - name: "setup docker"
    include_role:
      name: "einfachit.epic.docker"


- name: install argon fan control scripts
  hosts: argon_case
  become: true
  gather_facts: false
  tasks:

  - name: "Include argon case installation"
    include_role:
      name: "einfachit.epic.argon_case"
