---
- name: factory reset raspberry pi
  hosts: raspberries
  ignore_unreachable: yes
  strategy: free
  become: true
  gather_facts: false
  tasks:

  - name: reset machine to plain os by restoring image from a recovery partition
    ansible.builtin.command: /boot/boot_to_recovery restore
    async: 1000
    poll: 0
    notify:
      - remove hostname from known_host
      - set new ansible_hostname
      - wait to reboot after restore

  handlers:

  - name: remove hostname from known_hosts
    known_hosts:
      name: "{{ ansible_host }}"
      path: ~/.ssh/known_hosts
      state: absent
    delegate_to: localhost
    throttle: 1
    become: false
    changed_when: false

  - name: set new ansible_hostname
    set_fact: ansible_host="{{ raw_hostname }}.local"

  - name: wait to reboot after restore
    wait_for_connection:
      delay: 60
      timeout: 1000
