---
- name: decommission container
  hosts: container
  gather_facts: false
  connection: local
  tasks:
    
  - name: Wait for docker api to get available
    wait_for:
      port: 2375
      # host: "localhost"
      host: "{{ hostvars[docker_host].ansible_host }}"
      # search_regex: Connected
      timeout: 10
    vars:
      ansible_connection: local
    failed_when: false
    delegate_to: localhost
    when: docker_host != 'localhost'
    register: docker_api_connect

  - debug:
      var: docker_api_connect

  - block:

    - name: Delete container
      docker_container:
        name: "{{ inventory_hostname }}"
        docker_host: "{{ docker_api }}"
        container_default_behavior: no_defaults
        state: absent
      delegate_to: localhost

    - name: delete volumes
      docker_volume:
        name: "{{ item.name }}"
        state: absent
        docker_host: "{{ docker_api }}"
      delegate_to: localhost
      when: not (docker_keep_volumes | default(true))
      loop: "{{ docker_volumes | default([]) }}"

    when: docker_host == 'localhost' or docker_api_connect.elapsed < 10
