---
- hosts: container
  gather_facts: false
  connection: local
  tasks:
    
  - name: Wait for docker api to get available
    wait_for:
      port: 2375
      host: "{{ hostvars[docker_host].ansible_host }}"
      # search_regex: Connected
    vars:
      ansible_connection: local
    delegate_to: localhost
    when: docker_host != 'localhost'

  - name: create backup volume
    docker_volume:
      name: "{{ item.name }}"
      docker_host: "{{ docker_api }}"
    delegate_to: localhost
    loop: "{{ docker_volumes | default([]) }}"

  - name: construct mount strings
    ansible.builtin.set_fact:
      mount_string: "{{ item.name}}:{{ item.path }}"
    loop: "{{ docker_volumes | default([]) }}"
    register: mounts

  - name: prepare list of mount_strings
    ansible.builtin.set_fact:
      mount_strings: "{{ mounts.results | map(attribute='ansible_facts.mount_string') | list }}"

  - debug:
      var: mount_strings

  - name: Start container
    docker_container:
      name: "{{ inventory_hostname }}"
      image: "{{ image }}"
      volumes: "{{ mount_strings }}"
      command: ["sleep", "infinity"]
      docker_host: "{{ docker_api }}"
      container_default_behavior: no_defaults
    delegate_to: localhost
