---
- hosts: container
  gather_facts: false
  connection: local
  tasks:
    
  - name: Wait for docker api to get available
    wait_for:
      port: 2375
      host: "{{ hostvars[docker_host].ansible_host }}"
      # search_regex: Connected
    vars:
      ansible_connection: local
    delegate_to: localhost
    when: docker_host != 'localhost'

  - name: create backup volume
    docker_volume:
      name: home_backup
      docker_host: "{{ docker_api }}"
    delegate_to: localhost

  - name: Start container
    docker_container:
      name: "{{ inventory_hostname }}"
      image: "{{ image }}"
      volumes:
        - home_backup:/home
      command: ["sleep", "infinity"]
      docker_host: "{{ docker_api }}"
      container_default_behavior: no_defaults
    delegate_to: localhost
