---
- name: provision raspberries
  hosts: raspberries
  become: true
  gather_facts: false

  pre_tasks:

    - name: Set ansible host to raw_hostname
      ansible.builtin.set_fact:
        ansible_host: "{{ raw_hostname }}"

    - name: update apt cache with sudo apt-get --allow-releaseinfo-change update
      command: sudo apt-get --allow-releaseinfo-change update
      changed_when: false
      retries: 3 # maybe ntp time not yet synced
      delay: 3
      register: result
      until: result.rc == 0

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: apt
    
          #- name: Hold raspberrypi-kernel for bullseye
          #  dpkg_selections:
          #    name: raspberrypi-kernel
          #    selection: hold
          #  when: "'raspberrypi-kernel' in ansible_facts.packages"

          #- name: Hold raspberrypi-kernel for bookworm
          #  dpkg_selections:
          #    name: "{{ item }}"
          #    selection: hold
          #  loop: "{{ ansible_facts.packages | select('match', 'linux-image-rpi*' ) }}"

    - name: Upgrade the OS (apt-get upgrade)
      apt:
        upgrade: yes
        update_cache: yes
        lock_timeout: 600
      retries: 2
      throttle: 1


  tasks:

  - name: Gathering facts
    setup:

  - name: remove entry from known_hosts (initial hostname and ip adress)
    known_hosts:
      name: "{{ ansible_host }}"
      path: ~/.ssh/known_hosts
      state: absent
    delegate_to: localhost
    throttle: 1
    become: false
    changed_when: false

  - name: Set ansible hostname to ip address
    ansible.builtin.set_fact:
      ansible_host: "{{ ansible_default_ipv4.address }}"

  - name: Set a hostname
    ansible.builtin.hostname:
      name: "{{ hostname }}"
      use: systemd

  - name: update /etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.0\.1'
      line: "127.0.0.1 {{ hostname }}.{{ epic_domain }} {{ hostname }}"
      owner: root
      group: root
      mode: '0644'

  - name: Disalbe mdsn for ipv6 which may lead to issues (hostname already in use)
    ansible.builtin.lineinfile:
      path: "/etc/avahi/avahi-daemon.conf"
      regexp: '^use-ipv6=' 
      line: "use-ipv6=no"
      state: present

  - name: reboot server
    ansible.builtin.command: reboot
    async: 100
    poll: 0
    changed_when: false

  - name: remove entry from known_hosts (ip-address, original hostkey which will change after reboot)
    known_hosts:
      name: "{{ ansible_host }}"
      path: ~/.ssh/known_hosts
      state: absent
    delegate_to: localhost
    throttle: 1
    become: false
    changed_when: false

  - name: set ansible host to new hostname
    ansible.builtin.set_fact:
      ansible_host: "{{ hostname }}"

  - name: Wait 600 seconds, but only start checking after 60 seconds
    wait_for_connection:
      delay: 60
      timeout: 600
