# This is a basic workflow to help you get started with Actions

name: CI

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt -y upgrade
          curl -fsSL https://get.docker.com | sudo bash
          sudo apt install python3 python3-pip virtualenv
          virtualenv -p python3 venv
          source venv/bin/activate
          pip install ansible molecule molecule-docker yamllint
          
      - name: Build and Publish Collection
        shell: bash
        env:
          GALAXY_API_KEY: ${{ secrets.galaxy_api_key }}
        run: |
          source venv/bin/activate
          sed -i 's/version: 1.0.0/version: ${{ github.event.release.tag_name }}/' galaxy.yml
          ansible-galaxy collection build
          ansible-galaxy collection publish --token "$GALAXY_API_KEY" einfachit-epicserver-${{ github.event.release.tag_name }}.tar.gz


